apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: app-sealed-secret
  namespace: ressourcerie
spec:
  encryptedData:
    NOTION_INTEGRATION_TOKEN: AgB9BMjb9SsalJ3bOluQBKDHlNQ/gjhIsmHtn6yeDd96c4kj+s22XkMaJjTMkt6/Ee6YpZJ2OzDvYa+RWuHP4vpccbl9AOUCCQFLNvyAnYaUtDVso1NEZmLLEyjPdBA0OvQQQ5BQFzZv2kCrpu2LX7HP1Ybc78Voggd9KF7IjoUE4/gUEOllfu8ChZwdU2qFW1hG8U8phgustGd490T//+4NVB1Emtb/v5C4hCKCl4XSraxVAp7KcZIfnWcyvCt38Bn5IzO2AEIC4XtpjA5y6G6UXYqucWAOr99yh+EwvB2kMiVu2NhHTly5syXnrhxnH4q+s4FqnmYRN5m5xh1RbwJxMSSfQYaEBuSeB79ihEwzWxQZ1tgqbe/zgVe5HYZvvoboShzinyW++2ciRQenoajRs3tsCgFbkRJra6jZkcOvd9oRUZ4fzY/F3Kx4zV/sL+zuT+dppcI3ammO5gLN505dURIIyZHSo6A3qi+8h8axiP4LX82zbgCShJQl847FSK3h1/3dWSbN4/PzxxOfHaCGuP8fNV/XhX9wwaiYVMkQaLMONUQPUFRxL1Exv9AFRvvweEqFIU289a8dXEoMSLxtgYTNYIPXjCTmMeyglRf/XdS3XCyebEWgCOsSBpCg3PIgh3wiye4Q281UVYZ/kJ/UN8juCbmXpdNjgpxPCU1pjpSYZOx1tkH/SUpCbSpqu/Yzxr6tOyfkp0Cah547wvft84vn4osJrw7A9qOlfsrKsh8ydB3zfA98QHcKIGP/u04lTA==
  template:
    metadata:
      annotations: {}
      name: app-sealed-secret
    type: Opaque
