apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: app-sealed-secret
spec:
  encryptedData:
    NOTION_INTEGRATION_TOKEN: AgDG6FAYWxGNN0usFWJdBk78CACGUsikw8D5sC3AEAFxNn2abYckeZA6YZaJT/11yvHhChVWTWAGKb5Dng03WDt2sgUEM1GZHj9oBAVMQ/7ZIr/YYoBMbPWNI/BBkScTrREcdSk3geTnbLEAVWF+2Aks6tfKaLJxVh7+jEOPzwiUKOOufNEwuI7rO8Mfo+pT6Lu+0V8/x4UetNCQltvBMzjqT/Na3LUV4CiQMCzMH6yB8t9FoVQC9gNzuiQYRIqQETHV6XymMkq3UCkX/8c6Gp99OjJpi8j2bBAc8ydwkKn4Xp1F5PjR/OF3i/gokPhlQWI3jeVaYe7X2UNvWx2Sxkg3NcqUDN9kbBBEKkftodTHwUSFal7odzpj+wmUgHzNu3bpzFyP/Yen6qkH3iNYFGTmfu7Fsc2PtWTyAKcoI1LUP02unlkL/MjcZvlTRZYX78q3cBVuQQpr4R2UEvq9kehVuRHZjTcaZUiAVwV+cWuUaEzawSZodujt3Ghn0xwM+WLiUrxpo0xQozLT0ZKOsyVzO4aLoRTs0e5yPz0w1R3IZ8NonYMGkAepeeGN1r9EbQFc2szOqLGIXAzfI1QjOQ1ANC49mbqt/rRXr3zVsWhST4qBQgQv3kZKOzRLjWOxH8wCazlzGceGOgJxj3mpJSvaf6kyKyYEBEwON46IXjPJPC/WGv8vrxySARRmMGX54ilBSO8IL9hOdVEDCxVYboQkXcZOdxQoJ5q0imc+XhR6xQghSsJ+etsYS7ctDa5NK5R7Dg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: app-sealed-secret
    type: Opaque
