app:
  enabled: true
  env:
    - name: APP_BASE_URL
      value: 'https://{{ $.Values.global.host }}'
  envFrom:
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
  probesPath: /healthz
  replicas: 1
  imagePackage: app
